name: Create Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: npm install

      - name: Get Package Version
        id: get_version
        run: |
          package_version=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$package_version"
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_ENV

      - name: Fail if version already released
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          version_tag=v${{ env.PACKAGE_VERSION }}
          if npm view @rozetkapay/rozetka-pay-sdk-react-native@$version_tag > /dev/null 2>&1; then
            echo "Release ${version_tag} already exists."
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ env.PACKAGE_VERSION }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: "true"

  publish:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish